import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Font,
} from "@react-pdf/renderer";
import { ReportParts } from "../../utils/buildReportText";

// Define COLORS matching the previous theme
const PRIMARY_COLOR = "#334155";
const ACCENT_COLOR = "#3b82f6";
const TEXT_HEADING = "#334155";
const TEXT_BODY = "#475569";
const MUTED_COLOR = "#94a3b8";
const BG_METADATA = "#f9fbf3"; // Adjusted to match the subtle light blue/slate the user liked

const styles = StyleSheet.create({
  page: {
    paddingVertical: 40,
    paddingHorizontal: 54,
    backgroundColor: "#ffffff",
    fontFamily: "Helvetica",
    fontSize: 11.5,
    color: TEXT_BODY,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
    borderBottom: "0.5pt solid #e2e8f0",
    paddingBottom: 15,
  },
  brand: {
    fontSize: 13,
    fontWeight: "bold",
    color: ACCENT_COLOR,
  },
  reportType: {
    fontSize: 10,
    color: MUTED_COLOR,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: PRIMARY_COLOR,
    marginBottom: 25,
  },
  metadataSection: {
    backgroundColor: "#f9fbfc", // Subtle light blue/slate
    padding: 16,
    paddingVertical: 16,
    marginBottom: 20,
    flexDirection: "column",
    gap: 12,
    borderLeft: `3pt solid ${TEXT_HEADING}`,
    position: "relative",
  },
  metadataItem: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  metadataLabel: {
    width: 120, // Base width for labels
    fontSize: 9.5,
    fontWeight: "bold",
    color: TEXT_HEADING,
  },
  metadataValue: {
    flex: 1,
    fontSize: 10,
    color: TEXT_HEADING,
    fontWeight: "normal",
  },
  sectionHeading: {
    fontSize: 14,
    fontWeight: "bold",
    color: PRIMARY_COLOR,
    marginTop: 20,
    marginBottom: 15,
  },
  pointItem: {
    flexDirection: "row",
    marginBottom: 8,
    paddingLeft: 5,
  },
  bullet: {
    width: 15,
    color: ACCENT_COLOR,
    fontSize: 14,
    fontWeight: "bold",
  },
  pointText: {
    flex: 1,
    lineHeight: 1.2,
  },
  paragraph: {
    marginBottom: 12,
    lineHeight: 1.2,
  },
  footer: {
    position: "absolute",
    bottom: 25,
    left: 54,
    right: 54,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTop: "0.5pt solid #f1f5f9",
    paddingTop: 10,
    fontSize: 9,
    color: MUTED_COLOR,
  },
});

export function ReportDocument({
  title,
  docTypeLabel,
  formattedDate,
  fileName,
  mainPoints,
  summary,
}: ReportParts) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <View style={styles.header} fixed>
          <Text style={styles.brand}>DocLens</Text>
          <Text style={styles.reportType}>Document Analysis Report</Text>
        </View>

        {/* Content */}
        <Text style={styles.title}>{title}</Text>

        {/* Metadata section */}
        <View style={styles.metadataSection}>
          {fileName && (
            <View style={styles.metadataItem}>
              <Text style={styles.metadataLabel}>SOURCE FILE:</Text>
              <Text style={styles.metadataValue}>{fileName}</Text>
            </View>
          )}
          {docTypeLabel && (
            <View style={styles.metadataItem}>
              <Text style={styles.metadataLabel}>DOCUMENT TYPE:</Text>
              <Text style={styles.metadataValue}>
                {docTypeLabel.toUpperCase()}
              </Text>
            </View>
          )}
          {formattedDate && (
            <View style={styles.metadataItem}>
              <Text style={styles.metadataLabel}>DATE ANALYZED:</Text>
              <Text style={styles.metadataValue}>
                {formattedDate.toUpperCase()}
              </Text>
            </View>
          )}
        </View>

        {/* Key Findings */}
        <Text style={styles.sectionHeading}>Key Findings</Text>
        {mainPoints.length > 0 ? (
          mainPoints.map((point, index) => (
            <View key={index} style={styles.pointItem}>
              <Text style={styles.bullet}>•</Text>
              <Text style={styles.pointText}>{point}</Text>
            </View>
          ))
        ) : (
          <Text style={styles.paragraph}>(No main points available)</Text>
        )}

        {/* Overview */}
        <Text style={styles.sectionHeading}>Overview</Text>
        {summary.length > 0 ? (
          summary.map((para, index) => (
            <Text key={index} style={styles.paragraph}>
              {para}
            </Text>
          ))
        ) : (
          <Text style={styles.paragraph}>(No summary available)</Text>
        )}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>Generated by DocLens</Text>
          <Text
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}
